# 数据集参数
dataset_conf:
  # 过滤最短的音频长度
  min_duration: 0.5
  # 最长的音频长度，大于这个长度会裁剪掉
  max_duration: 5
  # 是否裁剪静音片段
  do_vad: true
  # 音频的采样率
  sample_rate: 44100
  # 是否对音频进行音量归一化
  use_dB_normalization: True
  # 对音频进行音量归一化的音量分贝值
  target_dB: -20
  # 训练数据的数据列表路径
  train_list: 'dataset/train_list_features.txt'
  # 评估注册的数据列表路径
  enroll_list: 'dataset/enroll_list_features.txt'
  # 评估检验的数据列表路径
  trials_list: 'dataset/test_list_features.txt'
  # 评估的数据要特殊处理
  eval_conf:
    # 评估的批量大小
    batch_size: 32
    # 最长的音频长度
    max_duration: 20
  # 数据加载器参数
  dataLoader:
    # 训练的批量大小
    batch_size: 32
    # 读取数据的线程数量
    num_workers: 4
    # 是否丢弃最后一个样本
    drop_last: True
  # 数据增强参数
  aug_conf:
    # 是否使用语速扰动增强
    speed_perturb: True
    # 使用语速增强是否分类大小翻三倍
    speed_perturb_3_class: True
    # 是否使用音量增强
    volume_perturb: False
    # 音量增强概率
    volume_aug_prob: 0.2
    # 噪声增强的噪声文件夹
    noise_dir: 'dataset/noise'
    # 噪声增强概率
    noise_aug_prob: 0.2
  # 是否使用SpecAug
  use_spec_aug: True
  # Spec增强参数
  spec_aug_args:
    # 随机频谱掩码大小
    freq_mask_width: [ 0, 8 ]
    # 随机时间掩码大小
    time_mask_width: [ 0, 10 ]

# 数据预处理参数
preprocess_conf:
  # 音频预处理方法，支持：MelSpectrogram、Spectrogram、MFCC、Fbank
  feature_method: 'MelSpectrogram'
  # 设置API参数，更参数查看对应API，不清楚的可以直接删除该部分，直接使用默认值
  method_args:
    sample_frequency: 44100
